### ISSUE TITLE
Icon name with symbol

### ISSUE THREAD

**Issue by gomo** [tomkra/font_awesome5_rails#12]
Hi @tomkra.
Thanks for quick support for rails 5.2 !

In the previous version I used, I could use the symbol for the icon name, but I can not use it v0.3.1.

```rb
fa_icon(:global)
```

```
undefined method `split' for :globe:Symbol

font_awesome5_rails/lib/font_awesome5_rails/parsers/parse_methods.rb:22:in `arr_with_fa'
font_awesome5_rails/lib/font_awesome5_rails/parsers/fa_icon_parser.rb:29:in `get_all_classes'
font_awesome5_rails/lib/font_awesome5_rails/parsers/fa_icon_parser.rb:17:in `classes'
font_awesome5_rails/app/helpers/font_awesome5/rails/icon_helper.rb:12:in `fa_icon'
```

I think that it is a problem that only string are assumed below. Is it possible to support symbol?

```rb
  def arr_with_fa(array)
    array.split(" ").map{ |s| prepend_fa(s) }
  end
```

**Comment by tomkra** [comment]
@gomo Hello, I've probably forget for symbol notation of old FA gem. I will include fix in next release.

**Comment by tomkra** [comment]
@gomo Hi, try update to version ```0.3.2```. You should now be able use use symbol for icon. If icon has has a dash in name like ```fa_icon 'camera-retro'``` It's posible to use symbol notation like this ```fa_icon :camera_retro```

**Comment by gomo** [comment]
@tomkra 

Thanks for the update! 👍
