### ISSUE TITLE
aria-hidden by default?

### ISSUE THREAD

**Issue by xinspire** [tomkra/font_awesome5_rails#16]
Can we have the fa_icon helper method include the `aria-hidden` attribute by default?

In reading [the official FA docs on accessibility](https://fontawesome.com/how-to-use/accessibility), I don't see a use case where aria-hidden wouldn't be present.

Thanks for considering!

**Comment by tomkra** [comment]
@xinspire You have right. Definitely should be default attribute, I will include fix in next version.

**Comment by tomkra** [comment]
@xinspire Hello, I've digged more into this. So when you use FA5 as SVG with JS ```aria-hidden``` tag is included by default (FA5 script autoinclude this). But when you use webfont version there was no option for including these tags. Now is possible to add this tags to ```fa_icon``` helper, but I didn't make them default in webfont vesion for two reasons:

Firstly in old gem from [font-awesome-rails](https://github.com/bokmann/font-awesome-rails), they are not default too.
Secondly In FA5 documentation, they are not default in ```i``` tags.

However if you upgrade to version ```0.3.3```, you will be able to use these tags optionally. Hope It's understandable.

For exapmle:
``` = fa_icon :camera, 'aria-hidden': true ```
