### ISSUE TITLE
Installation: "Old way" but with .scss?

### ISSUE THREAD

**Issue by futura** [tomkra/font_awesome5_rails#23]
Thanks a ton for the gem!

I started with the "recommended" installation, but I feel like the JavaScript conversion to SVG is interfering with some of my existing Javascript. I want to test by "downgrading" to the CSS only version, but I use .scss.

So in my application.js, I removed the
`require font_awesome5`

And in application.scss, I have:
```
@import 'font_awesome5';
@import 'font_awesome5_webfont';
```
Do I need both of these @imports? Only one? With this configuration, I'm seeing no icons at all.

**Comment by futura** [comment]
Maybe answering my own question ... after some experimentation, I believe this is correct.

Keep the `require` in the .js file but remove the plain, vanilla `@import 'font_awesome5'` in the .scss. So:

 application.js
`require font_awesome5`

application.scss
`@import 'font_awesome5_webfont';`

**Comment by tomkra** [comment]
@futura Hello, If you want to use webfont versions only, It should be working just with
 ```@import 'font_awesome5_webfont``` in your ```application.css.scss``` without any aditional imports or requires.
