### ISSUE TITLE
svg-with-js.min.css not included

### ISSUE THREAD

**Issue by overdrivemachines** [tomkra/font_awesome5_rails#27]
I am using option 1 for installation "Install as SVG with JS". I have included `@import 'font_awesome5';` in my application.scss but it does not import all the styles that are in svg-with-js.min.css. How can I import those styles as well?

**Comment by tomkra** [comment]
Hi @overdrivemachines , when you try to include it like this ```/* *= require font_awesome5 */ ``` is it work? Secondary you can try ```@import 'font_awesome5.css' ``` in your ```application.css```. 

Please let me know If any of these workarounds work. Thank you.
