### ISSUE TITLE
Add option to put text to the right of icon

### ISSUE THREAD

**Issue by moveson** [tomkra/font_awesome5_rails#34]
Using `fa_icon`, I can quickly create an element that combines a span with text and an icon. But the icon always appears first (on the left) with the text on the right.

I would like to have an option that puts the text on the left with the icon on the right. Following the syntax of other FA gems, it might look like this:

`fa_icon 'arrow-right', text: 'Continue', right: true`

**Comment by tomkra** [comment]
Hello @moveson, seems like a good feature to me :). I'll try to include this functionality in new version.

**Comment by tomkra** [comment]
Hi @moveson, I've added this functionality to last version ```0.6.0```.

**Comment by moveson** [comment]
Nice! Works great.
