### ISSUE TITLE
Pro icons not working

### ISSUE THREAD

**Issue by MakarovCode** [tomkra/font_awesome5_rails#35]
I've been trying to use the pro icons but can't make it work.
I download de SVG files, save them in **app/assets/svg folder**.

Add this line to **config/initializers/assets.rb**
`Rails.application.config.assets.precompile += %w( svg/* )`

Try using icons with both the HTML and GEM Helpers:
`<%= fa_icon('analytics', type: :fas) %>
<i class="fas fa-analytics"></i>
`

Restarted my server, not working!. What am I missing?

**Comment by parterburn** [comment]
@MakarovCode FA just released Kits a few days ago which makes using Pro icons with this gem much easier. See the updated Readme in the PR I just made: https://github.com/tomkra/font_awesome5_rails/pull/37

**Comment by tomkra** [comment]
@MakarovCode Sorry for slow response. I'm not using Pro icons so I didn't try this. Did you find the solution or steps proposed by @parterburn worked for you?

**Comment by MakarovCode** [comment]
Yes, it did work, I remove the next lines from application.scss and application.js
```
@import "font_awesome5";
//= require font_awesome5
```

And load the CDN (Kit) in my application.html.erb
`<script src="https://kit.fontawesome.com/xxxxxxxxx.js"></script>`

Very important is to check **Pro** in the Font Awesome Kit configuration.

**Comment by tomkra** [comment]
@MakarovCode Super, thank you for response. Closing for now. Feel free to reopen if you have any problem.

**Comment by chmich** [comment]
Hi, Like MakarovCode, it works for me.
But, is there a way to have all svgs inside the public-folder and the gem would drag the svgs from there?

reason: 
i'm not happy with the kit, i want to have no dependency for a yearly licence.
I also dont want to blow up my asset-pipeline with thousands of icons.

a little bit like the inline_svg gem, but for Font-Awesome, your gem is smarter.

Thanks,
Christian
