### ISSUE TITLE
name and future of gem

### ISSUE THREAD

**Issue by tomkra** [tomkra/font_awesome5_rails#40]
Hello to all using this gem. I've like to discuss two things related to this gem.

1. Since FontAwesome is currently at version ```5.9.0``` It will not take to much time since they realease sixth version of their amazing font. For us that means that name of this gem will no longer be valid.

    I think that make new gem for every major release of Font Awesome would be waste of time so **I propose to rename this gem to some more general name**. I thought something like **font_awesomeX_rails** or **font-awesomeX-rails**. 

    I would be grateful for any more ideas however If you propose same name, please make sure, that It is not already taken on [rubygems.org](https://rubygems.org/).

2. Secondly **rails 6** will be prefering webpack over the asset pipeline. I'm not much familiar with it at the moment, however I would like to know If there is interest to keep this gem as asset-pipeline related project or to move to completely to webpack and focus on it with new realeases.

Thank you, please feel free to comment.

**Comment by jrochkind** [comment]
I don't know if it's true that fontawesome 6 is coming soon. Have you seen any news of that, or are you just assuming from the version name? A fontawesome 5.10 is totally possible. fontawesome 5 was a pretty major change from 4, and took a while; I'm not sure a 6 will be anytime soon. 

There are already some rails gems that are named generically for fontawesome and _don't_ support 5, and seem to be abandoned. This having 5 in the name makes it easy to find googling for one that _does_ support 5. 

I'd leave the name alone for now, unless/until there's actually news of an upcoming fontawesome 6, I think it's a problem you don't have for now.

**Comment by KarlHeitmann** [comment]
Hi,

Today I searched for a gem to implement the latest font awesome with the latest rails version: Font Awesome 5 & Rails 6. I've reached this gem but also found the font_awesome_rails gem (with no number).

I don't know when Font Awesome 6 would get out, but I know that Rails 6 is about to come. What about in the moment when Rails 6 will came out, you make a new repo called: font_awesome_rails6, and on it you will support whatever is the latest font awesome version X integrated to Rails 6 ?

Only a suggestion, I think that you as the maintainer and developer of this project are the one qualified to take the shots. Whatever you choose will be the best option.

**Comment by LuckyGStar** [comment]
Hi,

As long as Github is designed for version control, I think we'd better to manage font-awesome in single repository with branches of version. I have a couple of suggestions. 

`1` : Change this repository name to `font-awesome-rails-stable` or anything like that? (not sure if it is good or not)
`2` : Leave this repository as it is  for version5 and make new repository with proper name.

Hope this should be helpful!

Cheers.

**Comment by VinylVault** [comment]
I agree with other commenters, I dont think FA6 will come anytime soon, so if you want to rename this gem, and to keep it relevant to different versions of G± and rails, maybe go with FA5-Rails5, FA5-Rails6 etc

Thanks for bringing FA5 to rails

**Comment by tomkra** [comment]
First of all, I want to thank everyone for your opinions. I've decided to keep the name of the gem as it is, including it's focus on asset pipeline. It's really very likely that the next version of FA5 will be 5.10, so let's wait.

About Rails6 and webpack part, maybe I will create separated gem which will only include `` fa_icon`` helpers and font itself will be installed via yarn or npm. I didn't tried to use this gem only with icon helpers and rest of font install through yarn (npm) but I think there shouldn't be a problem with it. 

Maybe in the future I will port these ```fa_icon``` helpers to javascript too, so It will be possible to use same helpers in rails views and javascript code too.

However thank you all once again for comments. I will keep this open in case that someone will have some other good ideas.

**Comment by krtschmr** [comment]
fa-rails

**Comment by tomkra** [comment]
I think I can close this thread for the moment. FA kept versioning a who knows when there will be version 6.
About webpack, I've updated Readme with instructions for webpack installation. I will keep bundling FA for asset pipeline with this gem and these who prefer webpack can install FA with it and use helpers from this gem. I've tested this with rails 6 and it works like a charm.
