### ISSUE TITLE
I'm Getting a Missing icon_header Error After Updating to Version 0.7.0

### ISSUE THREAD

**Issue by lightbe** [tomkra/font_awesome5_rails#42]
I was successfully running version 0.6.0. I did a bundle update like I usually do when getting ready to update my applications. I currently run Rails 5.2.3 with Ruby 2.5.2. Now when I run 0.7.0 or 0.6.0, I get the following error:

`ActionController::RoutingError (Couldn't find FontAwesome5::Rails::IconHelper, expected it to be defined in helpers/font_awesome5/rails/icon_helper.rb)`

When it was working a few months ago I used `*= require font_awesome5_webfont`. I tried this along with `@import 'font_awesome5_webfont';` in my stylesheet. Regardless, I get the above error. The file exists. I don't know where to look to try and find out if the problem is on my end.

UPDATE: 8 AM July 30, 2019 - I just tried upgrading to Ruby 2.6.3 running version 0.7.0. I got the same error. I'm using `@import "font_awesome5_webfont";` in my stylesheet.

**Comment by tomkra** [comment]
Hello @lightbe, did you solved your issue? If you still have this issue, maybe try increase asset version in ```assets.rb``` after ```bundle update```.

Second way is to try completely remove gem from your project and try it install from scratch. I'm using latest version in many projects including ruby-2.6.3 and didn't have problem.

Please let me know If It helped.

**Comment by lightbe** [comment]
I had another major problem that I needed to quickly fix in several of my applications when I had the problem this gem. I changed the gem to font-awesome-sass which is working well. If that gem quits working I will try using this one again.

**Comment by Nitrodist** [comment]
I ran into this running font_awesome5_rails (1.2.0)
