### ISSUE TITLE
fix blink problem with turbolinks

### ISSUE THREAD

**Issue by ehsanatwork** [tomkra/font_awesome5_rails#45]
Hello
I am trying to add `font awesome 5` on my `rails 5.2` project.
but it is showing the following errors.
`FontAwesome.config.mutateApproach = 'sync'; // fix blink problem with turbolinks`
 i have notice that, only `<%= fa_icon('user') %>` this tag is showing, but `<%= far_icon('camera-retro') %>` this is not working.
how can i solve this problem?
Thank you

**Comment by tomkra** [comment]
Hello @ehsanatwork, did you resolved your issue? Where exactly do you getting this error?
Please note that ```<%= far_icon('camera-retro') %> is only accessible in pro version of FontAwesome. In free version version (which is included with this gem) there is only solid type for this icon. So <%= fas_icon 'camera-retro' %> should work correctly.

You can check FA website https://fontawesome.com/icons/camera-retro?style=solid to get an overview which icon types are in pro and free version.

My testing project running on rails 5.2 and this line is required to prevent icons blinking when using it with turbolinks. It's just method call from FA lib and It should not cause any problems.

**Comment by ehsanatwork** [comment]
@tomkra Hello
Thank you for your valuable suggestion.
I did not know that, now i understand.
Thank you
