### ISSUE TITLE
Automatically add fa- to classes

### ISSUE THREAD

**Issue by Sylvain** [tomkra/font_awesome5_rails#5]
Hi! 
In the previous gem, when you add fw in the classes, it automatically added fa- prefix. For instance: 

`fa_icon('circle fw')`

would return:

`<i class="fa fa-home fa-fw"></i>`

Here, it returns:

`<i class="fas fa-circle fw"></i>`

I was wondering if it was done on purpose?

Many thanks for your help!

**Comment by tomkra** [comment]
Hello, I didn't know about this feature. I will implement this in next version.

**Comment by tomkra** [comment]
Hi, please update to version ```0.3.0```. This feature should be working now.

**Comment by Sylvain** [comment]
Many thanks for this!
