### ISSUE TITLE
Is it possible to add a class to each of the stacked icons?

### ISSUE THREAD

**Issue by romanbsd** [tomkra/font_awesome5_rails#55]
In font-awesome-rails the fa_stacked_icon helper had a :icon_options and :base_options option keys, which allowed to add classes (and any other options, really) to each of the icons in the span.
How is it possible to do in your implementation? The trivial use case is to add a class to the 'ban' icon to make it red (as in example: https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons)

Thanks!

**Comment by tomkra** [comment]
@romanbsd Sorry for late response, I didn't know about this. Currently It's not possible, but this is useful function so I will try to implement it during weekend.

**Comment by tomkra** [comment]
Sorry I didn't have time to get onto this. With version 1.2.0 you should be able to specify `fa_stacked_icon` attributes with `base_options` and `icon_options` as you suggested.
