### ISSUE TITLE
Apple icon is not able

### ISSUE THREAD

**Issue by kalashnikovisme** [tomkra/font_awesome5_rails#60]
Apple icon is able in free plan of font awesome, but in 1.3.0 it can't be used :(
https://fontawesome.com/icons?d=gallery&q=apple

**Comment by tomkra** [comment]
Hello, apple icon is working fine for me. It's brand icon so make sure youre calling it with appropriate helper like
`fab_icon 'apple'` or
`fa_icon 'apple', type: :brand`

Does this helped to you? If not, are you using only css version of font or javascript with svgs? Thank you.

**Comment by kalashnikovisme** [comment]
@tomkra yes, it's helped! thnx
