### ISSUE TITLE
Missing icons compared to the 'Free' pack

### ISSUE THREAD

**Issue by cornuwel** [tomkra/font_awesome5_rails#61]
Hi,

A quick grep shows there are about 708 icons in the gem, but https://fontawesome.com/icons?d=gallery&m=free shows 1609 free icons.

For my specific case, I'm trying to use 'creative-commons-nc' which is listed under https://fontawesome.com/icons?d=gallery&q=creative-commons&m=free but all I get is the flashing ?! icon, like the icon didn't exist (note, all my other icons work fine).

Am I missing something? Or is it just a case of adding the missing icons? Which I don't know how to do...

**Comment by tomkra** [comment]
Hi @cornuwel, 

when I grep icons in `/app/assets/images/` with `ls -lR | grep ".svg" | wc -l` command, I get 1604 icons - some icons were added in newest version.

Icon you are trying to display is packed as well. When you go to icon page [https://fontawesome.com/icons/creative-commons-nc?style=brands](https://fontawesome.com/icons/creative-commons-nc?style=brands) please notice, that icon type is **brand** icon.

When you call `fa_icon` helper, the default type is solid so you need to call your helper with type specified as this: `fa_icon('creative-commons-nc', type: :fab)` and that's it. I've tried and icon works normally. Hope this helps. For more info check the [docs](https://github.com/tomkra/font_awesome5_rails#solid-regular-light-brand-duotone-icon-types).

**Comment by cornuwel** [comment]
Sorry, twice. First, for only looking at https://raw.githubusercontent.com/bokmann/font-awesome-rails/master/app/assets/fonts/fontawesome-webfont.svg, and second for somehow skipping that part of the doc. And thank you :-)

**Comment by tomkra** [comment]
No need to apologize, I'm glad you've resolved your problem.
