### ISSUE TITLE
Set type option for each stacked icon

### ISSUE THREAD

**Issue by bhavyanshu** [tomkra/font_awesome5_rails#7]
There should be a way to define type for each stacked icon. 

For example,

```
<%= fa_stacked_icon "terminal inverse", base: "square", type: "fas", class: "fa-4x" %>
```
The above works perfectly fine.

But what if I want the terminal icon to be "fas" and the square icon to be "far". Is there already a way to define it? I couldn't find it in the documentation.

**Comment by tomkra** [comment]
Hi, I added this feature to version ```0.3.0```. You can now define different base icon type through ```base_type``` option.
