### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by nikolaokonesh** [tomkra/font_awesome5_rails#9]
![screenshot-2018-4-4 2gid](https://user-images.githubusercontent.com/6263853/38287607-4c8f519e-3817-11e8-99a5-198bffb3f14f.png)

not show brand.
gem version 0.3.0
rails 5.2.0.rc2 

and after update page with turbolinks icons disable.

**Comment by tomkra** [comment]
Hello, I've tested last gem version today with ruby  2.5.0 and rails 5.2.0.rc2 and everything seemed to be working fine(even with turbolinks) so I'm gonna need more info.

- Are you using ```webfont``` version or ```svg``` with ```js```?
- Do you have same problem with older gem version?
- Does problem occur on development environment?
- What icons not working for you?

Thank you for response.

**Comment by nikolaokonesh** [comment]
@tomkra 
1. i'm install as SVG with JS (recommended)
3. development environment.
4. Not working social icons.

`<%= fa_icon('camera-retro', animation: 'spin') %>` show. but after update page with turbolinks icon disable

мой английский "хреновый". Sorry

**Comment by nikolaokonesh** [comment]
@tomkra how u install this gem?

**Comment by tomkra** [comment]
Hello, you were right there were realy problem with turbolinks. I've updated gem and now should be working correctly with turbolinks. try update do version ```0.3.1```
